name: issue edited

on:
  issues:
    types:
      - edited

jobs:
  move-issue-to-backlog:
    name: move issue to backlog
    uses: bombshell-dev/automation/.github/workflows/move-issue-to-backlog.yml@main
    secrets:
        BOT_APP_ID: ${{ secrets.BOT_APP_ID }}
        BOT_PRIVATE_KEY: ${{ secrets.BOT_PRIVATE_KEY }}
